name: secretbin
services:
  secretbin:
    image: ghcr.io/secretbin-io/secretbin:latest-arm64
    container_name: secretbin
    read_only: true
    ports:
      - "8001:8000"
    volumes:
      - type: bind
        source: ./config.yaml
        target: /app/config.yaml
      - type: bind
        source: ./config.db.yaml
        target: /app/config.db.yaml
      - type: bind
        source: ./resources
        target: /app/resources
      - type: bind
        source: ./public
        target: /app/public
    networks:
      - secretbin

networks:
  secretbin:
